import * as THREE from 'three';
import { configWith } from '../src/config';
import { generateWorld } from '../src/sim/world';
import { TerrainSurface } from '../src/render/terrain/TerrainSurface';
import { SkyAtmosphere } from '../src/render/atmosphere/SkyAtmosphere';
import { DirectionalAtmosphereRig } from '../src/render/atmosphere/AtmosphericScattering';
import { resolveEnvironmentFrame } from '../src/render/atmosphere/EnvironmentFrameState';
const mode = new URLSearchParams(location.search).get('mode') ?? 'dusk';
const night = mode === 'night' ? 1 : mode === 'dusk' ? 0.15 : 0;
const world = generateWorld(configWith({ seed: 'skyline-review', world: { size: 32 } }));
const surface = new TerrainSurface(world);
const scene = new THREE.Scene();
const sky = new SkyAtmosphere(world, surface, 'skyline-review');
scene.add(sky.group, surface.buildApron(), surface.buildMesh('skyline-review'));
const elevation = mode === 'night' ? -0.3 : mode === 'day' ? 0.8 : 0.12;
const direction = new THREE.Vector3(0.8, elevation, 0.4).normalize();
const sun = new THREE.DirectionalLight('#ffe0af', (1 - night) * 3);
sun.position.copy(direction).multiplyScalar(100); scene.add(sun);
scene.add(new THREE.HemisphereLight('#a2b7cf', '#45404b', 0.15 + (1 - night) * 1.1));
sky.setPalette(new THREE.Color(night === 1 ? '#0a1226' : '#536b88'), new THREE.Color(night === 1 ? '#263248' : '#b8aaa0'));
new DirectionalAtmosphereRig(scene).update(resolveEnvironmentFrame({ sunElevation: elevation, sunDirection: direction, night,
 fogDensity: mode === 'storm' ? 0.05 : 0.0072, sourceExposure: 1, sourceFogColor: new THREE.Color('#89949e'), sourceBackground: new THREE.Color('#89949e') }));
const camera = new THREE.PerspectiveCamera(48, innerWidth / innerHeight, 0.1, 3000);
camera.position.set(0, surface.seaLevelY + 18, 0); camera.lookAt(220, surface.seaLevelY + 36, 95);
sky.followCamera(camera); sky.update(0, 0);
const renderer = new THREE.WebGLRenderer({ antialias: true }); renderer.setSize(innerWidth, innerHeight);
renderer.toneMapping = THREE.ACESFilmicToneMapping;
document.body.style.cssText = 'margin:0;overflow:hidden;background:#111'; document.body.append(renderer.domElement);
const errors: string[] = [];
renderer.debug.onShaderError = (gl, program) => { errors.push(gl.getProgramInfoLog(program) ?? 'shader error'); };
renderer.render(scene, camera);
const report = document.createElement('div'); report.style.cssText = 'position:fixed;bottom:20px;left:24px;color:white;font:14px system-ui';
report.textContent = `Skyline review ? ${mode} ? shader errors: ${errors.length} ? draw calls: ${renderer.info.render.calls}`;
document.body.append(report);
