import type { InfrastructureState, InstitutionKind, KnowledgeDomain, KnowledgeKind, Occupation, ResourceStock } from '../types';

export interface KnowledgeNeed {
  id: string;
  theory?: number;
  practice?: number;
}

export interface DiscoveryConditions {
  foundations?: KnowledgeNeed[];
  alternatives?: KnowledgeNeed[][];
  minPopulation?: number;
  resources?: Partial<Pick<ResourceStock, 'wood' | 'minerals' | 'goods' | 'wealth'>>;
  minFertility?: number;
  coastal?: boolean;
  occupations?: Partial<Record<Occupation, number>>;
  institutionsAny?: InstitutionKind[];
  minIndustrialIntensity?: number;
  minLiteracy?: number;
  /** Enabling conditions beyond prior knowledge: surplus, demand, and engineering capacity. */
  minInfrastructure?: Partial<InfrastructureState>;
  minTradeRoutes?: number;
  minFoodSecurity?: number;
  minProsperity?: number;
  minUrbanization?: number;
  pressure?: 'food' | 'climate' | 'conflict' | 'trade' | 'administration' | 'labor';
}

export interface KnowledgeDefinition {
  id: string;
  name: string;
  description: string;
  kind: KnowledgeKind;
  domain: KnowledgeDomain;
  difficulty: number;
  baseChance: number;
  major?: boolean;
  conditions: DiscoveryConditions;
}

const understanding = (id: string, name: string, domain: KnowledgeDomain, description: string, difficulty: number, baseChance: number, conditions: DiscoveryConditions = {}, major = false): KnowledgeDefinition => ({ id, name, domain, description, kind: 'understanding', difficulty, baseChance, conditions, major });
const practice = (id: string, name: string, domain: KnowledgeDomain, description: string, difficulty: number, baseChance: number, conditions: DiscoveryConditions = {}, major = false): KnowledgeDefinition => ({ id, name, domain, description, kind: 'practice', difficulty, baseChance, conditions, major });
const capability = (id: string, name: string, domain: KnowledgeDomain, description: string, difficulty: number, baseChance: number, conditions: DiscoveryConditions = {}, major = true): KnowledgeDefinition => ({ id, name, domain, description, kind: 'capability', difficulty, baseChance, conditions, major });

const need = (id: string, theory = 0.18, practiceLevel = 0.12): KnowledgeNeed => ({ id, theory, practice: practiceLevel });

/** A network of useful ideas, practices, and accomplishments—not an ordered era ladder. */
export const KNOWLEDGE_CATALOG: readonly KnowledgeDefinition[] = [
  understanding('fire-control', 'Controlled fire', 'energy', 'Reliable handling of heat, fuel, and flame.', 0.12, 0.08),
  understanding('seasonal-observation', 'Seasonal observation', 'agriculture', 'Recognizing recurring weather, growth, and harvest patterns.', 0.14, 0.07),
  practice('stone-composites', 'Composite stone tools', 'materials', 'Joining stone, fiber, resin, and wood into durable tools.', 0.15, 0.07, { resources: { wood: 5 }, occupations: { forager: 2 } }),
  practice('crop-selection', 'Crop selection', 'agriculture', 'Saving and propagating plants with useful inherited traits.', 0.3, 0.035, { foundations: [need('seasonal-observation', 0.22, 0.08)], minFertility: 0.48, occupations: { farmer: 5 }, pressure: 'food' }, true),
  understanding('leverage', 'Leverage and balance', 'mechanics', 'Practical understanding of force multiplied through distance and pivots.', 0.34, 0.03, { foundations: [need('stone-composites', 0.08, 0.2)], occupations: { builder: 2 } }),
  practice('irrigation', 'Managed irrigation', 'agriculture', 'Moving and storing water to stabilize cultivation.', 0.48, 0.022, { foundations: [need('seasonal-observation', 0.25, 0.1), need('leverage', 0.16, 0.12)], occupations: { farmer: 7, builder: 2 }, pressure: 'climate' }, true),
  capability('agrarian-surplus', 'Large-scale agricultural surplus', 'agriculture', 'Coordinated production and storage beyond immediate household needs.', 0.56, 0.026, { alternatives: [[need('crop-selection', 0.12, 0.42)], [need('irrigation', 0.12, 0.4)]], minPopulation: 48, occupations: { farmer: 12 }, pressure: 'food' }),
  practice('pottery-firing', 'Pottery firing', 'materials', 'Controlled firing of shaped clay into vessels and structural ceramics.', 0.3, 0.032, { foundations: [need('fire-control', 0.24, 0.18)], occupations: { artisan: 2 } }, true),
  understanding('material-testing', 'Material testing', 'materials', 'Comparing fracture, hardness, heat response, and durability.', 0.42, 0.025, { alternatives: [[need('stone-composites', 0.12, 0.3)], [need('pottery-firing', 0.12, 0.28)]], occupations: { artisan: 3 } }),
  understanding('combustion-dynamics', 'Combustion dynamics', 'energy', 'Recognizing how airflow, fuel, and containment alter heat.', 0.5, 0.019, { foundations: [need('fire-control', 0.36, 0.3)], occupations: { artisan: 3 }, institutionsAny: ['craft-circle', 'knowledge-keepers'] }),
  practice('high-temperature-ceramics', 'High-temperature ceramics', 'materials', 'Refractory vessels and structures that survive intense heat.', 0.66, 0.014, { foundations: [need('pottery-firing', 0.18, 0.48), need('combustion-dynamics', 0.38, 0.18)], resources: { minerals: 8 }, occupations: { artisan: 5 }, institutionsAny: ['craft-circle'] }, true),
  practice('metal-smelting', 'Metal smelting', 'materials', 'Separating workable metal from mineral-bearing material.', 0.58, 0.017, { foundations: [need('combustion-dynamics', 0.28, 0.15), need('material-testing', 0.3, 0.15)], resources: { minerals: 12, wood: 12 }, occupations: { artisan: 4 }, pressure: 'conflict' }, true),
  practice('iron-working', 'Iron working', 'materials', 'Repeated heating, shaping, and treatment of iron-rich material.', 0.74, 0.012, { foundations: [need('metal-smelting', 0.2, 0.48)], alternatives: [[need('high-temperature-ceramics', 0.16, 0.4)], [need('combustion-dynamics', 0.5, 0.24)]], resources: { minerals: 18 }, occupations: { artisan: 6 }, institutionsAny: ['craft-circle', 'military-order'] }, true),
  understanding('counting-measure', 'Counting and measure', 'records', 'Repeatable quantities, comparison, geometry, and accounting.', 0.34, 0.03, { occupations: { keeper: 2 }, pressure: 'trade' }, true),
  practice('durable-records', 'Durable records', 'records', 'External symbols capable of preserving speech, quantities, and agreements.', 0.58, 0.017, { foundations: [need('counting-measure', 0.38, 0.16)], minPopulation: 42, occupations: { keeper: 4, artisan: 2 }, institutionsAny: ['knowledge-keepers', 'council', 'merchant-association'], pressure: 'administration' }, true),
  capability('civic-administration', 'Distributed civic administration', 'records', 'Coordinating stores, obligations, and decisions across communities.', 0.66, 0.016, { foundations: [need('durable-records', 0.25, 0.46), need('counting-measure', 0.45, 0.22)], minPopulation: 60, institutionsAny: ['council', 'merchant-association'], pressure: 'administration' }),
  practice('printing', 'Repeatable printing', 'records', 'Reproducing durable symbols with reusable prepared surfaces.', 0.78, 0.01, { foundations: [need('durable-records', 0.55, 0.52)], alternatives: [[need('precision-tools', 0.18, 0.38)], [need('high-temperature-ceramics', 0.22, 0.46)]], resources: { goods: 18 }, occupations: { artisan: 5, keeper: 4 }, institutionsAny: ['knowledge-keepers'] }, true),
  understanding('buoyancy-currents', 'Buoyancy and currents', 'navigation', 'Recognizing displacement, stability, wind, and recurring water movement.', 0.38, 0.028, { coastal: true, resources: { wood: 10 }, occupations: { carrier: 3 } }),
  practice('celestial-navigation', 'Celestial navigation', 'navigation', 'Relating measured sky movements to position and seasonal travel.', 0.58, 0.017, { foundations: [need('buoyancy-currents', 0.34, 0.24), need('counting-measure', 0.3, 0.12)], coastal: true, occupations: { carrier: 5, keeper: 2 }, pressure: 'trade' }, true),
  capability('ocean-navigation', 'Open-water navigation', 'navigation', 'Sustained travel and provisioning beyond familiar coasts.', 0.7, 0.014, { foundations: [need('celestial-navigation', 0.32, 0.48), need('buoyancy-currents', 0.5, 0.46)], coastal: true, resources: { wood: 24, goods: 10 }, occupations: { carrier: 7 }, institutionsAny: ['merchant-association'] }),
  understanding('anatomical-observation', 'Anatomical observation', 'medicine', 'Accumulated comparison of injury, recovery, and bodily structure.', 0.4, 0.024, { minPopulation: 36, occupations: { keeper: 2 }, pressure: 'labor' }),
  understanding('contagion-patterns', 'Contagion patterns', 'medicine', 'Connecting contact, sanitation, and clustered illness.', 0.67, 0.013, { foundations: [need('anatomical-observation', 0.38, 0.2), need('durable-records', 0.24, 0.25)], minPopulation: 65, institutionsAny: ['knowledge-keepers', 'temple'] }, true),
  practice('vaccination', 'Protective inoculation', 'medicine', 'Deliberate controlled exposure that reduces later disease harm.', 0.86, 0.007, { foundations: [need('contagion-patterns', 0.58, 0.24), need('durable-records', 0.4, 0.42)], minPopulation: 75, institutionsAny: ['knowledge-keepers', 'temple'] }, true),
  understanding('pressure', 'Pressure and containment', 'mechanics', 'Relating confined fluids, heat, force, and vessel geometry.', 0.63, 0.014, { foundations: [need('leverage', 0.32, 0.24)], alternatives: [[need('pottery-firing', 0.2, 0.42)], [need('metal-smelting', 0.2, 0.34)]], occupations: { artisan: 4 }, institutionsAny: ['craft-circle', 'knowledge-keepers'] }, true),
  practice('wheel-axle', 'Wheel and axle systems', 'transport', 'Low-friction rotary transport and transmission of force.', 0.48, 0.022, { foundations: [need('leverage', 0.34, 0.3)], resources: { wood: 14 }, occupations: { builder: 3, carrier: 3 }, pressure: 'trade' }, true),
  capability('improved-roads', 'Engineered road networks', 'transport', 'Maintained all-weather routes with bridges, grading, and standards.', 0.62, 0.018, { foundations: [need('wheel-axle', 0.22, 0.42)], alternatives: [[need('civic-administration', 0.15, 0.36)], [need('counting-measure', 0.42, 0.2)]], resources: { wood: 20, wealth: 12 }, occupations: { builder: 5, carrier: 5 }, pressure: 'trade' }),
  practice('precision-tools', 'Precision tools', 'manufacturing', 'Repeatable fine measurement, cutting, and shaped working surfaces.', 0.68, 0.013, { foundations: [need('material-testing', 0.38, 0.24), need('counting-measure', 0.38, 0.2)], alternatives: [[need('iron-working', 0.18, 0.38)], [need('high-temperature-ceramics', 0.25, 0.44)]], occupations: { artisan: 6 }, institutionsAny: ['craft-circle'] }, true),
  practice('standardized-parts', 'Standardized parts', 'manufacturing', 'Interchangeable dimensions maintained across many makers.', 0.78, 0.01, { foundations: [need('precision-tools', 0.42, 0.5), need('durable-records', 0.3, 0.35)], minPopulation: 65, resources: { goods: 20 }, occupations: { artisan: 8 }, institutionsAny: ['craft-circle', 'merchant-association'] }, true),
  practice('rotary-machinery', 'Rotary machinery', 'mechanics', 'Continuous linked motion through shafts, bearings, gears, and cranks.', 0.76, 0.011, { foundations: [need('wheel-axle', 0.38, 0.48), need('precision-tools', 0.28, 0.38)], resources: { minerals: 18, goods: 14 }, occupations: { artisan: 7, builder: 3 }, institutionsAny: ['craft-circle'] }, true),
  understanding('thermodynamics', 'Heat and work', 'energy', 'General principles connecting heat flow, pressure, and mechanical work.', 0.9, 0.0065, { foundations: [need('pressure', 0.52, 0.25), need('combustion-dynamics', 0.52, 0.28), need('durable-records', 0.4, 0.35)], institutionsAny: ['knowledge-keepers'], occupations: { keeper: 5, artisan: 5 } }, true),
  capability('mechanical-power', 'Concentrated mechanical power', 'energy', 'Machines delivering sustained power beyond muscle, wind, or simple water work.', 0.92, 0.007, { foundations: [need('rotary-machinery', 0.25, 0.52), need('pressure', 0.42, 0.34)], alternatives: [[need('thermodynamics', 0.36, 0.12)], [need('combustion-dynamics', 0.62, 0.46)]], resources: { minerals: 24, goods: 22, wealth: 20 }, occupations: { artisan: 9, builder: 4 }, institutionsAny: ['craft-circle', 'merchant-association'] }),
  understanding('chemical-reactions', 'Chemical transformations', 'chemistry', 'Repeatable relationships among heat, minerals, solutions, and reaction products.', 0.78, 0.009, { foundations: [need('material-testing', 0.48, 0.26), need('high-temperature-ceramics', 0.26, 0.44), need('durable-records', 0.3, 0.3)], resources: { minerals: 18 }, occupations: { artisan: 6, keeper: 3 }, institutionsAny: ['knowledge-keepers', 'craft-circle'] }, true),
  capability('industrial-chemistry', 'Scaled chemical production', 'chemistry', 'Controlled repeatable chemical processes operating beyond workshop scale.', 0.94, 0.006, { foundations: [need('chemical-reactions', 0.5, 0.36), need('high-temperature-ceramics', 0.3, 0.56)], alternatives: [[need('mechanical-power', 0.16, 0.4)], [need('civic-administration', 0.3, 0.42)]], resources: { minerals: 28, goods: 24, wealth: 24 }, minPopulation: 70, institutionsAny: ['craft-circle', 'merchant-association'] }),
  capability('precision-manufacturing', 'Precision manufacturing', 'manufacturing', 'Reliable high-volume production within controlled dimensional tolerances.', 0.94, 0.006, { foundations: [need('standardized-parts', 0.35, 0.58), need('rotary-machinery', 0.28, 0.5)], resources: { minerals: 28, goods: 28, wealth: 25 }, minPopulation: 72, occupations: { artisan: 10 }, institutionsAny: ['craft-circle', 'merchant-association'] }),
  understanding('electromagnetism', 'Electromagnetic relationships', 'energy', 'Repeatable relationships among current, magnetism, motion, and conductive material.', 0.98, 0.0045, { foundations: [need('precision-tools', 0.5, 0.45), need('durable-records', 0.5, 0.42)], alternatives: [[need('chemical-reactions', 0.38, 0.2)], [need('mechanical-power', 0.22, 0.4)]], resources: { minerals: 30 }, occupations: { artisan: 8, keeper: 5 }, institutionsAny: ['knowledge-keepers'] }, true),
  capability('electrical-generation', 'Electrical generation', 'energy', 'Turning sustained mechanical or chemical processes into distributed electrical power.', 1.08, 0.004, { foundations: [need('electromagnetism', 0.52, 0.32), need('rotary-machinery', 0.38, 0.52)], alternatives: [[need('mechanical-power', 0.28, 0.52)], [need('industrial-chemistry', 0.34, 0.48)]], resources: { minerals: 34, goods: 30, wealth: 32 }, minPopulation: 78, institutionsAny: ['knowledge-keepers', 'merchant-association'] }),
  capability('rail-transport', 'Guided powered transport', 'transport', 'High-capacity vehicles constrained to precisely maintained routes.', 1.02, 0.0048, { foundations: [need('mechanical-power', 0.3, 0.58), need('improved-roads', 0.22, 0.42), need('iron-working', 0.25, 0.5), need('precision-tools', 0.24, 0.42)], minInfrastructure: { roads: 0.3, workshops: 0.3 }, minTradeRoutes: 2, minFoodSecurity: 0.45, minProsperity: 0.35, resources: { minerals: 38, goods: 28, wealth: 34 }, minPopulation: 75, occupations: { builder: 6, carrier: 7 }, institutionsAny: ['merchant-association', 'council'] }),
  practice('scientific-method', 'Experimental science', 'physics', 'Institutions compare measurements, publish methods, and reproduce disputed results.', 1.02, 0.0048, { foundations: [need('printing', 0.35, 0.42), need('counting-measure', 0.58, 0.38)], alternatives: [[need('anatomical-observation', 0.52, 0.32)], [need('material-testing', 0.58, 0.38)]], minLiteracy: 0.34, institutionsAny: ['knowledge-keepers'] }, true),
  capability('electric-grid', 'Interconnected electrical systems', 'energy', 'Generation, distribution, control, and maintenance form a shared power network.', 1.1, 0.0038, { foundations: [need('electrical-generation', 0.5, 0.56), need('precision-manufacturing', 0.35, 0.48)], alternatives: [[need('civic-administration', 0.42, 0.45)], [need('improved-roads', 0.45, 0.5)]], minIndustrialIntensity: 0.12, minInfrastructure: { workshops: 0.32 }, minUrbanization: 0.3, resources: { minerals: 40, goods: 35, wealth: 38 } }),
  capability('internal-combustion', 'High-density combustion transport', 'transport', 'Compact engines convert chemical energy into mobile mechanical work.', 1.1, 0.0035, { foundations: [need('thermodynamics', 0.5, 0.28), need('precision-manufacturing', 0.42, 0.55)], alternatives: [[need('industrial-chemistry', 0.42, 0.48)], [need('mechanical-power', 0.62, 0.62)]], minIndustrialIntensity: 0.14, minInfrastructure: { roads: 0.3 }, resources: { minerals: 38, goods: 34 } }),
  capability('modern-medicine', 'Modern clinical medicine', 'medicine', 'Public health, controlled trials, sanitation, and manufactured treatments reduce preventable death.', 1.08, 0.0042, { foundations: [need('contagion-patterns', 0.58, 0.38), need('scientific-method', 0.38, 0.3)], alternatives: [[need('vaccination', 0.35, 0.45)], [need('industrial-chemistry', 0.4, 0.36)]], minLiteracy: 0.36, institutionsAny: ['knowledge-keepers', 'council'] }),
  capability('mass-communication', 'Mass electronic communication', 'records', 'Information crosses large distances rapidly through electrical networks.', 1.12, 0.0035, { foundations: [need('electromagnetism', 0.58, 0.38), need('printing', 0.46, 0.5)], alternatives: [[need('electric-grid', 0.22, 0.3)], [need('electrical-generation', 0.58, 0.6)]], minIndustrialIntensity: 0.12, minLiteracy: 0.4 }),
  understanding('flight-dynamics', 'Controlled flight dynamics', 'aerospace', 'Lift, drag, stability, and propulsion become predictable enough for controlled flight.', 1.12, 0.0033, { foundations: [need('scientific-method', 0.42, 0.32), need('celestial-navigation', 0.42, 0.4)], alternatives: [[need('thermodynamics', 0.5, 0.24)], [need('electromagnetism', 0.52, 0.24)]], institutionsAny: ['knowledge-keepers'] }, true),
  capability('aviation', 'Powered aviation', 'aerospace', 'Reliable powered craft carry people and goods through the atmosphere.', 1.18, 0.003, { foundations: [need('flight-dynamics', 0.56, 0.36), need('precision-manufacturing', 0.5, 0.58)], alternatives: [[need('internal-combustion', 0.35, 0.5)], [need('electric-grid', 0.48, 0.46)]], minIndustrialIntensity: 0.2, resources: { minerals: 44, goods: 42, wealth: 40 } }),
  capability('computation', 'Programmable computation', 'computation', 'General symbolic procedures are executed by repeatable machines.', 1.16, 0.0034, { foundations: [need('counting-measure', 0.66, 0.52), need('scientific-method', 0.4, 0.32)], alternatives: [[need('precision-manufacturing', 0.54, 0.58), need('mechanical-power', 0.45, 0.48)], [need('electromagnetism', 0.58, 0.42), need('electric-grid', 0.3, 0.38)]], minLiteracy: 0.45 }),
  understanding('atomic-theory', 'Quantitative atomic physics', 'physics', 'Matter and radiation are described through experimentally testable atomic models.', 1.22, 0.0028, { foundations: [need('scientific-method', 0.58, 0.46), need('electromagnetism', 0.58, 0.4)], alternatives: [[need('industrial-chemistry', 0.58, 0.48)], [need('computation', 0.36, 0.3)]], minLiteracy: 0.48, institutionsAny: ['knowledge-keepers'] }, true),
  capability('biotechnology', 'Controlled biotechnology', 'biology', 'Living systems are measured and deliberately modified for medicine, agriculture, and industry.', 1.2, 0.0028, { foundations: [need('modern-medicine', 0.48, 0.52), need('scientific-method', 0.52, 0.44)], alternatives: [[need('industrial-chemistry', 0.5, 0.52)], [need('computation', 0.4, 0.32)]], minIndustrialIntensity: 0.2 }),
  capability('automation', 'General industrial automation', 'computation', 'Sensors, control systems, and programmable machines perform complex production tasks.', 1.2, 0.003, { foundations: [need('computation', 0.48, 0.46), need('precision-manufacturing', 0.58, 0.62)], alternatives: [[need('electric-grid', 0.48, 0.52)], [need('mass-communication', 0.38, 0.34)]], minIndustrialIntensity: 0.26 }),
  capability('rocketry', 'Guided high-energy rocketry', 'aerospace', 'Controlled high-energy propulsion and guidance operate beyond atmospheric flight.', 1.24, 0.0027, { foundations: [need('flight-dynamics', 0.58, 0.42), need('precision-manufacturing', 0.58, 0.62)], alternatives: [[need('internal-combustion', 0.52, 0.58), need('industrial-chemistry', 0.5, 0.52)], [need('electric-grid', 0.58, 0.52), need('computation', 0.38, 0.34)]], minIndustrialIntensity: 0.28, resources: { minerals: 48, goods: 48, wealth: 48 } }),
  capability('nuclear-fission', 'Practical nuclear fission', 'physics', 'Controlled atomic reactions release energy vastly beyond chemical combustion.', 1.3, 0.0024, { foundations: [need('atomic-theory', 0.6, 0.42), need('scientific-method', 0.62, 0.52)], alternatives: [[need('industrial-chemistry', 0.58, 0.58), need('precision-manufacturing', 0.62, 0.62)], [need('computation', 0.5, 0.46), need('electric-grid', 0.52, 0.58)]], minIndustrialIntensity: 0.3, resources: { minerals: 52, goods: 52, wealth: 55 } }),
  capability('satellite-systems', 'Artificial satellites', 'aerospace', 'Communication, observation, and navigation instruments operate in sustained orbit.', 1.28, 0.0026, { foundations: [need('rocketry', 0.48, 0.56), need('computation', 0.5, 0.46)], alternatives: [[need('mass-communication', 0.48, 0.48)], [need('scientific-method', 0.66, 0.52)]], minIndustrialIntensity: 0.3 }),
  capability('orbital-capability', 'Sustained orbital capability', 'aerospace', 'Reusable institutions and infrastructure repeatedly reach and operate in orbit.', 1.34, 0.0022, { foundations: [need('satellite-systems', 0.52, 0.58), need('rocketry', 0.6, 0.66), need('computation', 0.52, 0.5)], minIndustrialIntensity: 0.36, resources: { minerals: 58, goods: 58, wealth: 64 } }),
  capability('nuclear-energy', 'Civil nuclear energy', 'energy', 'Controlled fission supplies heat and electrical power under sustained operation.', 1.32, 0.0025, { foundations: [need('nuclear-fission', 0.48, 0.42), need('electric-grid', 0.5, 0.58)], alternatives: [[need('civic-administration', 0.55, 0.5)], [need('computation', 0.44, 0.4)]], minIndustrialIntensity: 0.32 }),
  practice('nuclear-medicine', 'Nuclear medicine', 'medicine', 'Radiation and isotopes are used for observation and treatment under controlled conditions.', 1.28, 0.0027, { foundations: [need('nuclear-fission', 0.42, 0.3), need('modern-medicine', 0.54, 0.6)], alternatives: [[need('scientific-method', 0.68, 0.54)], [need('biotechnology', 0.36, 0.4)]] }, true),
  capability('nuclear-propulsion', 'Nuclear propulsion', 'aerospace', 'Atomic energy supports propulsion beyond conventional chemical endurance.', 1.42, 0.0018, { foundations: [need('nuclear-fission', 0.62, 0.58), need('rocketry', 0.62, 0.68)], alternatives: [[need('computation', 0.58, 0.54)], [need('orbital-capability', 0.48, 0.55)]], minIndustrialIntensity: 0.42 }),
  capability('machine-intelligence', 'Machine decision systems', 'computation', 'Learning and inference systems assist science, production, and institutional decisions.', 1.34, 0.0022, { foundations: [need('computation', 0.62, 0.62), need('automation', 0.48, 0.54)], alternatives: [[need('mass-communication', 0.5, 0.54)], [need('scientific-method', 0.7, 0.56)]], minIndustrialIntensity: 0.38 }),
  capability('general-machine-systems', 'Highly capable general machine systems', 'computation', 'Machine systems transfer competence across scientific, economic, and strategic domains.', 1.5, 0.0015, { foundations: [need('machine-intelligence', 0.68, 0.68), need('automation', 0.62, 0.66), need('computation', 0.72, 0.72)], alternatives: [[need('biotechnology', 0.48, 0.46)], [need('mass-communication', 0.62, 0.66)]], minIndustrialIntensity: 0.48 }),
  capability('interplanetary-capability', 'Interplanetary transport systems', 'aerospace', 'Sustained transport and life-support networks operate between planetary bodies.', 1.52, 0.0014, { foundations: [need('orbital-capability', 0.7, 0.72), need('automation', 0.55, 0.62)], alternatives: [[need('nuclear-propulsion', 0.52, 0.58)], [need('rocketry', 0.76, 0.8), need('electric-grid', 0.68, 0.72)]], minIndustrialIntensity: 0.52, resources: { minerals: 70, goods: 70, wealth: 78 } }),
  capability('space-resource-industry', 'Off-world resource industry', 'aerospace', 'Automated extraction and processing operate beyond the home world.', 1.58, 0.0012, { foundations: [need('interplanetary-capability', 0.58, 0.62), need('automation', 0.68, 0.72)], alternatives: [[need('general-machine-systems', 0.44, 0.4)], [need('nuclear-propulsion', 0.6, 0.62)]], minIndustrialIntensity: 0.56 }),
];

export const KNOWLEDGE_BY_ID = new Map(KNOWLEDGE_CATALOG.map((definition) => [definition.id, definition]));

export const MAJOR_KNOWLEDGE_IDS = KNOWLEDGE_CATALOG.filter((definition) => definition.major).map((definition) => definition.id);
